Installation:

Download and install the Julia from this site https://julialang.org/downloads/

Run the following commands in the terminal to install Jupyter Notebook:

In [ ]:
using Pkg
Pkg.add("IJulia")

In [ ]:
using IJulia
notebook()

Reference:

https://github.com/JuliaLang/IJulia.jl

https://medium.com/@Jernfrost/types-in-c-c-and-julia-ce0fcbe0dec6

https://en.wikibooks.org/wiki/Introducing_Julia/Dictionaries_and_sets

https://en.wikibooks.org/wiki/Introducing_Julia/Arrays_and_tuples

STRING

A string consists of multiple characters. Double quotes or triple double quotes can be used to initialize a string. (Triple quotes is used to include quotes in a string)

In [5]:
str1 = "Hello, World!"
str2 = """Hellow, World"""
println(str1)
println(str2)

Hello, World!
Hellow, World


The index of the string in Julia starts from 1 instead of 0.

"end" is used to indicate the index of the last element in the string.

In [107]:
str = "Hello, World!"
println(str[1]) 
println(str[end]) 

H
!


There are two ways to get the substring:

(1) use index range. Note the index starts from 1.

(2) use SubString(string, starting index, end index).

In [108]:
println(str[2:4])
println(SubString(str, 2, 4))

ell
ell


String concatenation: 

string(str1, str2, str3...) is used to combine multiple strings. In the print statement, string() can be omitted.

In [109]:
println(string(str, "! ", ".\n\nEnd"))
println(str, "! ", ".End")

Hello, World!! .

End
Hello, World!! .End


The following functions can be used to find the index of a certain character:

(1) findfirst(isequal(char), string) finds the index of the character in the string that occurs first(leftmost)

(2) finglast(isequal(char), string) finds the index of the character in the string that occurs last(rightmost)

In [110]:
println(findfirst(isequal('o'), "xylophone"))
println(findlast(isequal('o'), "xylophone"))

4
7


(3) findnext(isequal(char), string, index) finds the index of the character in the string after a certain index

(4) findprev(isequal(char), string, index) finds the index of the character in the string before a certain index

In [111]:
println(findnext(isequal('o'), "xylophone", 1))
println(findnext(isequal('o'), "xylophone", 5))
println(findprev(isequal('o'), "xylophone", 5))

4
7
4


Other functions:

(1) occusin(str1, str2) is used to check if str2 contains a str1.

(2) $ symbol evaluate the value of an expression in a string

In [112]:
println(occursin("world", "Hello, world."))
println("1 + 2 = $(1 + 2)")
println("Test: $str")

true
1 + 2 = 3
Test: Hello, World!


COMPLEX NUMBER

In Julia, the complex number i is stored as a global constant im, representing the square root of -1. Do not use i because it may be used in other places such as a for loop.

In [13]:
function f(w, x, y, z)
    complex(w, x) * complex(y, z)
end
# 8 + 1im
println(f(1, 2, 2, -3))

8 + 1im


EXCEPTION

Like Java, we can use throw to throw an exception. Note that it must contain brackets, or it will become a type of exception instead of a specific one.

In [14]:
# Throw an exception
# Cannot get a square root of a negative number
function printSqrt(x)
    if x < 0
        throw(DomainError())
    else 
        println(sqrt(x))
    end
end

# must contain brackets
println(typeof(BoundsError()) <: Exception)
println(typeof(BoundsError) <: Exception)

true
false


To define an error, we can use the function error() with a string that contains the error message in the brackets:

In [15]:
function printSqrt(x)
    n >= 0 || error("Given number must be greater or equal to 0")
    println(sqrt(x))
end

printSqrt (generic function with 1 method)

Here is an example of try/catch statement

We are allowed to store the exception caught into a variable, so we can get information of the exception in the future. (just like “catch (Exception e)” in Java)

In [16]:
# try/catch statement
# can save exception in a variable
function foo(x)
    try
        sqrt(x)
    catch y
        if isa(y, DomainError)
            sqrt(-x)
        end
    end
end

foo (generic function with 1 method)

The code in finally will be ran after the code in try has been ran, or an exception or return happened in try. This is often used when operations of a file has been done( we need to close the file).

In [12]:
# usage of finally
# happens after an exception is thrown, 
# return or code successfully ran
function foo(x)
    try
        x = sqrt(x)
    finally 
        if x != nothing
            println(x)
        end
    end
end

foo (generic function with 1 method)

TYPE

:: is used to declare the type and error message is displayed if the number doesn't match the declared type. Uncomment the last command and run the code to see the error message

In [3]:
# Type declaration
(1)::Int64
(1.4)::Float64
# (1.4)::Int64
# Cast
num = Int32(1)

1

Another operation is the "child <: parent", which indicates the hierarchy. Here are some examples:

In [114]:
println(Integer <: Real)
println(Real <: Integer)

true
false


Then we can introduce new abstract type. Abstract type cannot be initialized and can be introduced by the keyword "abstract type" In order to define the parent type, we can use ":<" which is optional. We can use abstract type to let the compiler decide which specific function to use, like this:

In [115]:
abstract type newtype  <:  Integer end
println(newtype <: Real)
println(Real <: newtype)

true
false


FUNCTION

Function is a section in the program that performs certain tasks. There are two ways to initialize a function:

(1) The following way is clear but takes more time and space to write

In [17]:
function g(x,y) # equals to g(x::Any, y::Any)
    x * y
end

g (generic function with 1 method)

(2) Putting everything in one line is concise but it can be confusing sometimes.

In [117]:
f(x,y) = x + y
println(f(1,2), " ", g(1,2))

3 2


We can use :: to check the parameter's type and an error message is generated if the types don't match

In [118]:
function ftype(x::Int) 
    return x + 1
end
println(ftype(5))
# Generate an error message
println(ftype(5.5))

6


MethodError: MethodError: no method matching ftype(::Float64)
Closest candidates are:
  ftype(!Matched::Int64) at In[118]:2

We can also return multiple values with tuple/array. We cannot notice the difference by only looking at the returned values, but we can use typeof() and see the difference. Note the default returned type, in this case, is a tuple.

In [119]:
function fg(a,b)
    a+b, "string"
end
println(fg(1,2))

(3, "string")


The fg function will return a tuple with the first element as Int, and the second as a string

In [120]:
x, y = fg(2,3)
print(typeof(fg(2,3)))
println(":\t x = ", x, "; y = ", y)

Tuple{Int64,String}:	 x = 5; y = string


We can also return it as an Array.

In [121]:
function fg2(a,b)
    [a+b, "string"]
end
x, y = fg2(2,3)
print(typeof(fg2(2,3)))
println(":\t x = ", x, "; y = ", y)

Array{Any,1}:	 x = 5; y = string


CONTROL FLOW

The conditional statement in many programming languages(C/Python) can be put in one line. Similarly, we can also put the if else statement into one line.

In [122]:
function cmp(x, y)
    if x < y
        println("x is less than y")
   elseif x > y
        println("x is greater than y")
   else
        println("x is equal to y")
   end
end
cmp(9,1)

# condition ? true : false
cmp1(x, y) = println(x < y ? "x is less than y"    :
                            x > y ? "x is greater than y" : "x is equal to y")
cmp1(0,1)

x is greater than y
x is less than y


Compound expression is a sequence of statements and the last expression is evaluated and returned. It's different from the function. The variables used inside the compound expression can be accessed outside.

In [123]:
z = begin
   x = 1
   y = 2
   x + y
end
println(z, " = ", x, " + ", y) #parameters inside can be accessed(not like a function)
z = (a = 2; b = 2; a + b)
println(z, " = ", a, " + ", b)

3 = 1 + 2
4 = 2 + 2


LOOP

The while loop and for loop in Julia work similar to other languages, such as Python/Java. Just be careful with the infinite loop when using the while loop.

In [124]:
i = 0
while i < 5
   print(i, " ")
   i += 1
end
println()
for i = 0: 4
    print(i, " ")
end

0 1 2 3 4 
0 1 2 3 4 

The nested loop in Julia is easier to use. Here is an example:

In [125]:
for i = -1:2, j = 0:3
   print(i,j, " ")
end

-10 -11 -12 -13 00 01 02 03 10 11 12 13 20 21 22 23 

We can also use for each loop. Note the variable cannot be used outside of the loop.

In [126]:
for s in ["foo","bar","baz"]
   print(s, " ")
end
print(s) # Error message expected

foo bar baz 

UndefVarError: UndefVarError: s not defined

We can use "break" to end the loop or use "continue" to execute the next turn. Using "continue" will not execute any code after it in this turn.

In [127]:
i = 0
while true
   print(i, " ")
   if i >= 5
       break
   end
   global i += 1
end

println()
for i = 1:10
   if i % 3 != 0
       continue #only print 3,6,9
   end
   print(i, " ")
end

0 1 2 3 4 5 
3 6 9 

Composite types are called objects in Java, composite types are the mostly common used user-defined type in Julia. Composite types contains fields. In Julia, all values are object but functions are not bounded with objects. The way it works is similar to C.

In [128]:
struct name
    first::String
    last::String
end
tname = name("Tom", "Smith")
println(tname,"\t", tname.first, "\t", tname.last)

name("Tom", "Smith")	Tom	Smith


We can also add functions to the new object. Like C, we need to pass the new object as a parameter in the function. The order of the parameters doesn't matter but it has to match when you call the function. 

By default, Julia creates immutable objects, which doesn't allow modification of the values. So we also need to declare the constructor with "mutable struct" instead of "struct".

In [129]:
mutable struct Point
    x::Int #check the type
    y::Int
end

function addx(p::Point, xadd::Int64)
    p.x += xadd
end

function addy(yadd::Int64, p::Point)
    p.y += yadd
end

p = Point(4, 1)
println(p)
addx(p, 12)
addy(1,p)
println(p)

Point(4, 1)
Point(16, 2)


The difference between mutable and immutable types is about the identity of the object. We created a new name "Tom Smith" in the previous example. If we created another name with exactly the same name and compare these two objects, they are considered identical.

In [130]:
pname = name("Tom", "Smith")
println(tname == pname)

true


However, if we create two mutable objects with the same value, they are not considered the same. When creating a new type, we should consider if two objects with the same information are considered identical. For example, two persons can have the same name but they are not identical.

In [131]:
mutable struct Person
    fname::String
    lname::String
end
p1 = Person("Tom", "Smith")
p2 = Person("Tom", "Smith")
println(p1 == p2)

false


Parametric Constructors have more flexibility in Julia. The constructor can accept more than one value types by using "<:". You can go to TYPE section if you are not sure the use of "<:". In the following example, T is a child of the real numbers and x, y are T type. 

We can create new Point1 instance implicitly or explicitly. If we construct a new Point implicitly, the T will be assigned to the type of the passed value. If we pass integers, x and y will be integers. The other way is to explicitly define the type when creating a new instance. See the following example:

In [132]:
struct Point1{T<:Real}
   x::T
   y::T
end
println(Point1(1,2)) #implicit
println(Point1(1.2,2.0)) #implicit
println(Point1{Float64}(1,2))#explicit

Point1{Float64}(1.0, 2.0)
Point1{Float64}(1.2, 2.0)
Point1{Float64}(1.0, 2.0)


Sometimes we want to accept the input regardless of the types and convert the "wrong" types into the ones we want. There is a way to do this(a better way to do this??):

In [133]:
Point1(x::Int64, y::Int64) = Point1(convert(Float64,x),convert(Float64,y))
Point1(x::Float64, y::Int64) = Point1(x,convert(Float64,y))
Point1(x::Int64, y::Float64) = Point1(convert(Float64,x),y)
println(Point1(4, 1))
println(Point1(4, 1.9))
println(Point1(4.3, 1.9))

Point1{Float64}(4.0, 1.0)
Point1{Float64}(4.0, 1.9)
Point1{Float64}(4.3, 1.9)


DICTIONARY

The way the dictionary works in Julia is similar to Python. The dictionary has two parts, key, and value. Each key is unique and refers to a value. Let's look at some ways to initialize the dictionary.

(1) Dict(key => value, key => value...) is used when we know the key(s) and value(s). The type of the key/value is determined by the values in the dictionary. If all the keys/values are the same type, the type of key will be changed accordingly. Otherwise, it will be Any to accept any type of key/value.

(2) Dict{Key type, Value type}() is used when we know the key type and value type. In this case, we will get an error message if we pass the incorrect type. Note that the Key type and Value type can be "Any" to accept any type of data. 

(3) Dict() is used to initialize a dictionary with any types. In this case, the type doesn't change even all the keys in the dictionary are the same type.

Note:

See dict1 in the following example. You may notice that only 3 keys are actually in dict1 even we tried to add four keys. The reason is the key in a dictionary must be unique, so instead of adding a new identical key 1, the value of key 1 is updated. 

In [134]:
# (1)
dict = Dict("1" => "wrong value", 1 => "first")
dict1 = Dict(1 => "wrong value", 2 => "second", 3 => "third", 1 => "first")
println("Dict\t", typeof(dict), "\t", dict)
println("Dict1\t", typeof(dict1), "\t", dict1)

# (2)
dict2 = Dict{Int, String}()
i = 1
for s in ["first","second","third"]
    dict2[i] = s
    i = i + 1
end
println("Dict2\t", typeof(dict2), "\t", dict2)

# (3)
dict3 = Dict()
dict3["test"] = "good"
dict3[1] = "first"
println("Dict3\t", typeof(dict3), "\t\t", dict3)

Dict	Dict{Any,String}	Dict{Any,String}("1"=>"wrong value",1=>"first")
Dict1	Dict{Int64,String}	Dict(2=>"second",3=>"third",1=>"first")
Dict2	Dict{Int64,String}	Dict(2=>"second",3=>"third",1=>"first")
Dict3	Dict{Any,Any}		Dict{Any,Any}("test"=>"good",1=>"first")


We can get the value of the key by Dict[key], but it can raise an error if the key is not found. Uncomment the second line to see the error.

To avoid the error message, we can either add a try-catch statement or use get(dictionary, key, default). The default can be string or number and will be returned if the key is not in the dictionary.

In [135]:
println(dict1[1])
# println(dict1["2"])
println("default value = ",get(dict1, "2", 1))

first
default value = 1


To get all the keys or values in the dictionary, we can use keys(dictionary) and values(dictionary).

In [136]:
print(keys(dict1), "\t")
println(values(dict1))

[2, 3, 1]	["second", "third", "first"]


We can easily iterate over the dictionary in a for each loop. Don't forget the parentheses.

In [137]:
for (k, v) in dict1
    println(k, " -> ", v)
end

println()
for tuple in dict1
    println(tuple[1], " -> ", tuple[2])
end

2 -> second
3 -> third
1 -> first

2 -> second
3 -> third
1 -> first


haskey(dictionary, key) checks if the key is in the dictionary

in((key => value), dictionary) checks if the pair is in the dictionary

In [138]:
println("\n", haskey(dict1, 4), "\t", haskey(dict1, 2))
println(in((2 => "first"), dict2), "\t", in((2 => "second"), dict2), "\n")


false	true
false	true



DataStructure is available to use if we want to sort the dictionary.

In [139]:
# import DataStructures
# dict = DataStructures.SortedDict("b" => 2, "c" => 3, "d" => 4, "e" => 5, "f" => 6)

for key in sort(collect(keys(dict1))) # print the key in a sorted order
    println(key, " -> ", dict1[key])
end

1 -> first
2 -> second
3 -> third


delete!(dict, key) is used to delete the key

In [140]:
delete!(dict1, 1)
println("\nDict1: ", dict1)


Dict1: Dict(2=>"second",3=>"third")


ARRAY

Here are some functions we can use to initialize an array:

zeros(data type, 1st dimension, 2nd dimension,...) returns an array filled with zeros.

In [141]:
zeros(Int8, 1, 8)

1×8 Array{Int8,2}:
 0  0  0  0  0  0  0  0

Julia also allows us to use list comprehension just like Python.

In [142]:
array1 = [i for i=1:8] # list comprehension

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6
 7
 8

reshape(array, dimension 1, dimension 2...) is used to re-structure the array in a certain dimension. collect(starting value, step value, stop value) can be used to generate arrays.

In [143]:
array1 = reshape(array1, 2, 4)
# reshape(collect(0:10:99), 2, 5)

2×4 Array{Int64,2}:
 1  3  5  7
 2  4  6  8

fill(value, dimension 1, dimension 2...) is similar to zeros() but can fill any data type in the array.

In [144]:
fill("a", 3, 2)

3×2 Array{String,2}:
 "a"  "a"
 "a"  "a"
 "a"  "a"

repeat(A, n, m) is used to generate a larger array by repeating. A is the smaller array. n is the number of the times to repeat in the first dimension(row). m is the number of the times to repeat in the second dimension(column). (it can be tricky)

In [145]:
repeat([1,2,3], 1, 3) # [3x1] repeats 1 time in 1st dimension and 3 times in 2nd dimension => 3x3

3×3 Array{Int64,2}:
 1  1  1
 2  2  2
 3  3  3

In [146]:
repeat([1,2,3], 3, 1) # [3x1] repeats 3 times in the 1st dimension and 1 time in 2nd dimension => [9x1]

9×1 Array{Int64,2}:
 1
 2
 3
 1
 2
 3
 1
 2
 3

In [147]:
repeat([1 2 3], 3, 1) # [1x3) repeats 3 times in the 1st dimension and 1 time in 2nd dimension => [3x3]

3×3 Array{Int64,2}:
 1  2  3
 1  2  3
 1  2  3

In [148]:
repeat([1 2 3], 1, 3) # [1x3) repeats 1 time in 1st dimension and 3 times in 2nd dimension => [1x9]

1×9 Array{Int64,2}:
 1  2  3  1  2  3  1  2  3

Julia provides a really easy way for us to work with the array. vcat(array 1, array 2) combines array 2 and array 1 vertically, which adds new columns.

In [149]:
vcat(array1, [9 10 11 12]) #3x4 array

3×4 Array{Int64,2}:
 1   3   5   7
 2   4   6   8
 9  10  11  12

hcat(array 1, array 2) combines array 2 and array 1 horizontally, which adds new rows. Note that both functions don't change the array 1, so don't forget to assign the value to some variable. 

In [150]:
hcat(array1, [0; -1])

2×5 Array{Int64,2}:
 1  3  5  7   0
 2  4  6  8  -1

Just like what we usually do with an array, we can use array[index] to get the element in an array. The difference is, again, the index starts from 1 instead of 0. ":" is used to get all the elements at that dimension. 

In [151]:
println(array1[1],"\t", array1[end])
println(array1[:, end], "\t", array1[end, :])

1	8
[7, 8]	[2, 4, 6, 8]


In a for each loop, we can easily get the values in the array. If we also want to get the index, we should use enumerate(array) and put parentheses to return a tuple.

In [152]:
array2 = ["element1", "e2", "e3"]
for n in array2
    print(n, "\t")
end
println()
for (n, element) in enumerate(array2)
   println("array($(n)) = ", element)
end

element1	e2	e3	
array(1) = element1
array(2) = e2
array(3) = e3


The following functions can return the index of some value in array: findfirst(condition, array), findall(condition, array), findnext(condition, array). The condition can be functions like isequal(), iseven() or expression x-> x==something. Note that the findall() returns an array of index.

In [153]:
println(array2)
println("e3's index = ", findfirst(x-> x == "e3", array2))
println(array1)
println(findall(iseven, array1))

["element1", "e2", "e3"]
e3's index = 3
[1 3 5 7; 2 4 6 8]
CartesianIndex{2}[CartesianIndex(2, 1), CartesianIndex(2, 2), CartesianIndex(2, 3), CartesianIndex(2, 4)]


Other common function in an array:

ndim(array) returns the dimension of the array

size(array) returns the size of the array in the format of (dimension 1, dimension 2,...)

length(array) returns the total number of the data in the array

count(condition, array) returns the number of the data that satisfies the condition. The condition can be isequal(), iseven(), or expressions like x-> x==something.

sum(array) adds all the numbers together. You will get an error message if the elements are not numbers.

findmax(array) returns the maximum in the array.

extrema(array) returns a tuple with minimum maximum

In [154]:
println("Array1: dimension = ", ndims(array1), ", size = ", size(array1), ", length = ", length(array1), 
    ", count = ", count(iseven, array1))
println("sum = ", sum(array1), ", max = ", findmax(array2), ", extrema = ", extrema(array1))

Array1: dimension = 2, size = (2, 4), length = 8, count = 4
sum = 36, max = ("element1", 1), extrema = (1, 8)
